### ISSUE TITLE
Password hide/show toggle icon does not show on mobile.

### ISSUE THREAD

**Issue by liquidcms** [ionicthemes/ionic4-full-starter-app#3]
I have added the login/signup/forgot-password pages to my app and the mostly seem to be working as expected.

In Chrome, the hide/show toggle looks and works fine; but when build for Android and running on my device, the icon does not display (if you tap in the correct spot it does work though).

**Comment by djabif** [comment]
That's weird, it's a simple svg icon. Do you see the other icons form the app? which device are you using?

**Comment by liquidcms** [comment]
I see my footer icons and your back button icon. See screenshot: 
![Screenshot_2019-06-04-14-26-32](https://user-images.githubusercontent.com/355815/58904261-2c3f1b00-86d5-11e9-8c86-da7d50adcb30.png)

I am using an LG G6

**Comment by djabif** [comment]
Did you copy those icons to your project?
"./assets/sample-icons/auth/eye-show.svg"
"./assets/sample-icons/auth/eye-hide.svg"

**Comment by liquidcms** [comment]
hmm.. interesting.. ok, a couple issues with this:

1. your: "how to use this template" has no mention of this
2. it does work in Chrome, just not device
3. you didnt say where to copy to. Does it need to be exact path still assests/icons/auth?

i am adding now and rebuilding.

**Comment by liquidcms** [comment]
yes, they work now. I had assumed these were standard ionic icons - you might want to mention somewhere that you have assets required for some of your pages. :(

**Comment by djabif** [comment]
We designed many custom icons for this template and you are free to use them if you like. All of them are located in the `src/assets/sample-icons` folder. If you want to use them you need to include them in your project. I will add this to the docs. Thanks for the feedback.
