### ISSUE TITLE
Privacy/Terms modals do not open.

### ISSUE THREAD

**Issue by liquidcms** [ionicthemes/ionic4-full-starter-app#4]
I have added the signup/terms/privacy pages to my app and the page seems to look ok and function as expected. I also have merged in utils/components/themes. One thing which is not working is the modal to open the Privacy and Terms pages. 

Debugging the signup.page.ts i can see that the code is run when the privacy or terms links are clicked; but nothing opens and there are no errors.

**Comment by djabif** [comment]
Please try to serve the app in your browser and open the console to see if there is any message. We use the modal like in this example https://ionicframework.com/docs/api/modal#usage

**Comment by liquidcms** [comment]
Yes, this is in browser and as i mentioned.. no console errors.

Also does not work on real device.

**Comment by djabif** [comment]
Can you please publish it to firebase (or where you prefer) and send me a link so I can try it? 
Thanks

**Comment by liquidcms** [comment]
publish what, zip of project or just the apk? 

i'll email links

**Comment by liquidcms** [comment]
solved: my app.component.html did not match yours; this was causing the modals to not appear (also caused toast to not show).
