### ISSUE TITLE
Walkthrough pages showing up every time user starts the application

### ISSUE THREAD

**Issue by dunlop9** [ionicthemes/ionic4-full-starter-app#6]
Walkthrough pages are supposed to be shown only once when the user opens app for the first time. But the page keeps showing up everytime the user opens the application. Can you fix it or direct to documentation on how that can be addressed?

Also, once user is logged in, we shouldn't force user to login everytime. Only when application cache is cleared, we can ask for re-login. Can you point to documentation on how we can achieve it?

**Comment by djabif** [comment]
Hi @dunlop9, you can use [Ionic Storage](https://ionicframework.com/docs/building/storage#ionic-storage) to set up a flag to show/hide the walkthrough. For authentication screens I would suggest to check upon your auth DB if the current user is already logged in and then redirect him to the corresponding route. In this [ionic firebase tutorial](https://ionicthemes.com/tutorials/about/building-a-ionic-firebase-app-step-by-step) we have an example of how to do this.
